### ISSUE TITLE
create a gaussian process likelihood emulator for errors / log-likelihood

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#388] opened 2018-06-18 11:41 UTC
- Initially this will wrap GPy (we will see how we can do this without requiring Pints users to install it unless needed)
- The GP would take an error/log-likelihood and then train the GP to emulate this 
- Maksym is joining us for the summer. He will code this up and provide a notebook example of its use

**Comment by MichaelClerx** [comment] 2019-02-12 08:07
@martinjrobins can we close #45 as a duplicate of this?

**Closed** 2019-02-12 09:33 UTC
Labels: feature
