### ISSUE TITLE
Integrating the noise out

### ISSUE THREAD

**Issue by sanmitraghosh** [pints-team/pints#325] opened 2018-04-04 11:25 UTC
This is to remind @ben18785 about investigating integrated likelihood for both single and multiple outputs/series problems. This could be added to the existing set of known and unknown noise likelihoods.

**Comment by ben18785** [comment] 2019-02-20 03:57
Duplicate of #318 (which is now a PR #731) and so closing.

**Closed by ben18785** 2019-02-20 03:57 UTC
Labels: feature
