### ISSUE TITLE
Add nested sampling tutorial Jupyter notebook.

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#130] opened 2017-12-06 02:40 UTC
This is nearly done, but want to polish it before committing...

**Comment by MichaelClerx** [comment] 2018-02-12 13:34
https://github.com/pints-team/pints/blob/master/examples/inference-nested-sampling.ipynb

It's in! Does still need a bit of work though (missing a link and runs very very slowly)

**Comment by MichaelClerx** [comment] 2018-07-31 12:39
Closed as duplicate of #424

**Closed by MichaelClerx** 2018-07-31 12:39 UTC
Labels: documentation, priority
