### ISSUE TITLE
Restructuring Controller objects (especially run())

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#969] opened 2019-09-26 21:32 UTC
The Optimiser and Sampler classes (MCMC, Nested, ABC, and any future ones) all have quite similar functioning; especially, the run() method. They do something like:

1. instantiate counters
2. determine whether sensitivities are needed
3. determine whether to run in serial or parallel
4. set up logging (and whether to save to disk)
5. run method: each time doing some sort of ask and tell and updating loggers and counters until a stopping criterion is met
6. final log to screen

Of course, details about each of these differ. But, to me, this similarity makes me think we could save us work (and make things simpler to upkeep) if we refactored things like:

- Controller abstract base class
  - OptimiserController
  - SamplerController:
    - MCMCController
    - NestedController
    - ABCController

This isn't just a coding simplification issue. It's because I'm fearful that, when replicating other Controller methods, I miss stuff off. I also fear that idiosyncratic differences appear between the controllers that aren't anything to do with how they function; rather because they were created using different designs.

**Comment by MichaelClerx** [comment] 2019-09-26 21:58
We can think about it, but low priority: Let's focus on bugs and suggested minor improvements first!

**Comment by ben18785** [comment] 2019-09-26 22:01
@MichaelClerx Completely agree. Just a bit biased as I've been writing a few of these controllers recently and see how repetitious things are.

**Comment by MichaelClerx** [comment] 2019-09-26 22:19
It's a good thing to flag up (and funnily enough corresponds with that tool's opinion #919)
Will try and give this some thought in 2020 :-D

My first thought is that the controllers are already quite complex, so that adding in inheritance - unless it works naturally somehow - might not make things better. So it might be good to consider other options, e.g. defining helper classes/methods for common tasks

**Comment by MichaelClerx** [comment] 2020-03-31 18:00
Duplicate of #919

**Closed by MichaelClerx** 2020-03-31 18:00 UTC
Labels: code-and-design
