### ISSUE TITLE
Investigate gradient-based optimisation algorithms

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#283] opened 2018-03-24 01:22 UTC
You guys have probably thought about this but I was wondering about trying the following algorithms out in the optimisation side of things,

- stochastic gradient descent with/without momentum or with Nesterov momentum,
- adagrad,
- RMSprop with/without Nesterov momentum,
- Adam.

There are also second order methods that we could look into,

- Newton's method,
- conjugate gradients,
- BFGS.

I have seen these all being used with statistical inference problems before and I wondered about their use.

**Comment by martinjrobins** [comment] 2018-03-24 07:00
+1 for the stochastic gradient descent methods, I've been wanting to implement some of these. The second order ones would be fairly trivial, just need to wrap scipy.optimise (scipy already in dependencies). I think the main design change would be allowing models to return gradients.

**Comment by MichaelClerx** [comment] 2018-03-26 09:19
Scipy has a bunch of them that we could wrap. None of them work for ion channel problems so I'm not super interested myself :-)

**Comment by MichaelClerx** [comment] 2018-04-27 13:41
See also #55 and #54

**Comment by MichaelClerx** [comment] 2019-02-12 07:52
Duplicate of #684

**Closed by MichaelClerx** 2019-02-12 07:52 UTC
Labels: feature
